/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './lib/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#7F77DD',
        'primary-dark': '#534AB7',
        'primary-soft': '#EEEDFE',
        'primary-text': '#3C3489',
        ink: '#1A1A2E',
        surface: '#F7F7FC',
        'body-text': '#444441',
        'body-text-muted': '#6A6A66',
        'gray-border': '#E0DED8',
        white: '#FFFFFF',
        amber: '#EF9F27',
        'amber-soft': '#FAEEDA',
        'amber-text': '#633806',
        'amber-mid': '#EF9F2766',
        destructive: '#E24B4A',
        'cat-gray-bg': '#F1EFE8',
        'cat-gray-text': '#444441',
        'cat-teal-bg': '#E1F5EE',
        'cat-teal-text': '#085041',
        'cat-coral-bg': '#FAECE7',
        'cat-coral-text': '#993C1D',
        'cat-purple-bg': '#EEEDFE',
        'cat-purple-text': '#3C3489',
        'cat-blue-bg': '#E6F1FB',
        'cat-blue-text': '#0C447C',
        'cat-amber-bg': '#FAEEDA',
        'cat-amber-text': '#633806',
      },
      fontFamily: {
        display: ['Nunito_800ExtraBold'],
        'display-bold': ['Nunito_700Bold'],
        'display-semibold': ['Nunito_600SemiBold'],
        body: ['DMSans_400Regular'],
        'body-medium': ['DMSans_500Medium'],
      },
      borderRadius: {
        badge: '20px',
        button: '12px',
        card: '16px',
        'icon-btn': '10px',
        modal: '20px',
        input: '10px',
        logo: '14px',
      },
    },
  },
  plugins: [],
};
